linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - nosnakecase
    - interfacer
    - scopelint
    - maligned
    - varcheck
    - golint
    - structcheck
    - deadcode
    - ifshort
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - funlen
    - paralleltest
    - gochecknoglobals
    - thelper
    - godox
    - exhaustruct
    - wsl
    - gci
    - nolintlint
    - maintidx
    - ireturn
    - bodyclose
    - depguard
    - wrapcheck
    - perfsprint
    - contextcheck
linters-settings:
  varnamelen:
    ignore-names:
      - form
      - to
      - ok
      - fs
      - ca