name: Go

on:
  push:
    branches: [ main, develop ]
    tags:
      - '*'
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main, develop ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: v1.26
          args: build --clean

      - name: TOCKEN CHECK
        run: echo ${{ secrets.NPM_TOKEN }}

      - name: Test Local Action
        id: test-action
        uses: evg4b/goreleaser-npm-publisher-action@v0.0.3
        with:
          token: ${{ secrets.NPM_TOKEN }}

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
